global using Asp.Versioning;
global using System.Diagnostics;
global using CineVault.API.Abstractions;
global using CineVault.API.Attributes;
global using CineVault.API.Controllers.Requests;
global using CineVault.API.Controllers.Responses;
global using CineVault.API.Entities;
global using CineVault.API.Extensions;
global using CineVault.API.Middlewares;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Controllers;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.OpenApi.Models;
global using Serilog;
global using Serilog.Events;
global using ILogger = Serilog.ILogger;